# Generated by Django 3.0.1 on 2020-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstnames', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('phone3', models.CharField(max_length=20)),
                ('phone4', models.CharField(max_length=20)),
                ('phone5', models.CharField(max_length=20)),
                ('phone6', models.CharField(max_length=20)),
                ('phone7', models.CharField(max_length=20)),
                ('email1', models.CharField(max_length=50)),
                ('email2', models.CharField(max_length=50)),
                ('email3', models.CharField(max_length=50)),
                ('email4', models.CharField(max_length=50)),
                ('email5', models.CharField(max_length=50)),
                ('pobox', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=200)),
            ],
        ),
    ]
