# Generated by Django 3.0.1 on 2020-04-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200426_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgType', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='firstnames',
            new_name='firstNames',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=200)),
                ('orgNameShort', models.CharField(max_length=50)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('phone4', models.CharField(blank=True, max_length=20)),
                ('phone5', models.CharField(blank=True, max_length=20)),
                ('phone6', models.CharField(blank=True, max_length=20)),
                ('phone7', models.CharField(blank=True, max_length=20)),
                ('email1', models.CharField(blank=True, max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50)),
                ('email3', models.CharField(blank=True, max_length=50)),
                ('email4', models.CharField(blank=True, max_length=50)),
                ('email5', models.CharField(blank=True, max_length=50)),
                ('pobox', models.CharField(blank=True, max_length=20)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('orgType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.OrganisationType')),
            ],
        ),
    ]
