# Generated by Django 3.0.1 on 2020-04-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200426_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='orgNameShort',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
