# Generated by Django 3.0.1 on 2020-04-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200426_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstNames', models.CharField(blank=True, max_length=100)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('phone3', models.CharField(blank=True, max_length=20)),
                ('phone4', models.CharField(blank=True, max_length=20)),
                ('phone5', models.CharField(blank=True, max_length=20)),
                ('phone6', models.CharField(blank=True, max_length=20)),
                ('phone7', models.CharField(blank=True, max_length=20)),
                ('email1', models.CharField(blank=True, max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50)),
                ('email3', models.CharField(blank=True, max_length=50)),
                ('email4', models.CharField(blank=True, max_length=50)),
                ('email5', models.CharField(blank=True, max_length=50)),
                ('pobox', models.CharField(blank=True, max_length=20)),
                ('town', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('organisation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.OrganisationType')),
            ],
        ),
    ]
