# Generated by Django 3.0.1 on 2020-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200426_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='group',
            field=models.ManyToManyField(to='contacts.Group'),
        ),
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
