# Generated by Django 3.0.1 on 2020-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200426_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='group',
            field=models.ManyToManyField(blank=True, to='contacts.Group'),
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(blank=True, to='contacts.Group'),
        ),
    ]
