# Generated by Django 3.0.1 on 2020-04-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200426_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email1',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email2',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email3',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email4',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='email5',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email1',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email2',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email3',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email4',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='email5',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
