# Generated by Django 3.0.1 on 2020-04-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200427_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='website',
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
