# Generated by Django 3.0.1 on 2020-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('createDate', models.DateField()),
                ('modifyDate', models.DateField()),
                ('homepageDisplay', models.BooleanField()),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('imageTitle', models.ImageField(upload_to='articles/images/')),
                ('imageTitleCaption', models.CharField(blank=True, max_length=300)),
                ('image2', models.ImageField(blank=True, upload_to='articles/images/')),
                ('image2Caption', models.CharField(blank=True, max_length=300)),
                ('image3', models.ImageField(blank=True, upload_to='articles/images/')),
                ('image3Caption', models.CharField(blank=True, max_length=300)),
                ('image4', models.ImageField(blank=True, upload_to='articles/images/')),
                ('image4Caption', models.CharField(blank=True, max_length=300)),
                ('image5', models.ImageField(blank=True, upload_to='articles/images/')),
                ('image5Caption', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
