# Generated by Django 3.0.1 on 2020-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200424_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modifyDate',
            field=models.DateField(blank=True),
        ),
    ]
