# Generated by Django 3.0.1 on 2020-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200427_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='pobox',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='town',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
