# Generated by Django 3.0.1 on 2020-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='file',
            field=models.FileField(upload_to='articles/images/'),
        ),
    ]
