# Generated by Django 3.0.1 on 2020-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200427_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('postDate', models.IntegerField()),
                ('jobFile', models.FileField(upload_to='articles/images/')),
            ],
        ),
    ]
