# Generated by Django 3.0.1 on 2020-04-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_jobposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosts',
            new_name='JobPost',
        ),
    ]
