# Generated by Django 3.0.1 on 2020-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200427_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='postDate',
            field=models.DateField(),
        ),
    ]
