# Generated by Django 3.0.1 on 2020-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200427_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150)),
            ],
        ),
    ]
