# Generated by Django 3.0.1 on 2020-04-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_newslettersubscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSubscribers',
            new_name='NewsletterSubscriber',
        ),
    ]
