# Generated by Django 3.0.1 on 2020-04-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200429_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwacRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('atawasmember', models.BooleanField(blank=True, null=True)),
                ('organisationatawasmember', models.BooleanField(blank=True, null=True)),
                ('exhibitor', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
