# Generated by Django 3.0.1 on 2020-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_awacregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awacregistration',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
