# Generated by Django 3.0.1 on 2020-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20200429_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awacregistration',
            name='atawasmember',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are you a member of ATAWAS?'),
        ),
        migrations.AlterField(
            model_name='awacregistration',
            name='exhibitor',
            field=models.BooleanField(blank=True, null=True, verbose_name='Would you also like to be an exhibitor?'),
        ),
        migrations.AlterField(
            model_name='awacregistration',
            name='organisationatawasmember',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is your organisation a member of ATAWAS?'),
        ),
    ]
